apiVersion: v1
metadata:
  name: {{.Values.projectName}}-projmanwebdav-configs
  labels:
    app.kubernetes.io/name: {{ include "projmanwebdav.name" . }}
    helm.sh/chart: {{ include "projmanwebdav.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
kind: ConfigMap
data:
  {{- range $key, $entry := .Values.configs -}}
  {{- if $entry -}}
  {{- $key | nindent 4 }}: |
    {{- $entry | nindent 8 }}
  {{- end -}}
  {{- end -}}
